#!/bin/bash

if [ -z "$1" ]; then
  echo "usage: amterm <host> [<port>]"
  exit 1
fi
HOST=$1
PORT=$2
SOCK="${HOST}-${PORT}"

if [ -z "$PORT" ]; then
  PORT=5000
fi

socat PTY,link=${SOCK} TCP-CONNECT:${HOST}:${PORT} &
pid=$!
sleep 0.5
[ -r ${SOCK} ] || exit
screen ${SOCK}
kill $pid

