#!/bin/bash

if [ -z "$1" ]; then
  echo "usage: amterm <host> [<port>]"
  exit 1
fi
HOST=$1
PORT=$2
if [ -z "$PORT" ]; then
  PORT=5000
fi
exec screen -t ${HOST} socat STDIO TCP-CONNECT:${HOST}:${PORT}
